// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VXSocial is the predicate function for vxsocial builders.
type VXSocial func(*sql.Selector)
