// Code generated by ent, DO NOT EDIT.

package ent_work

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huoayi/business-center-ent-private/pkg/ent_work/order"
	"github.com/huoayi/business-center-ent-private/pkg/ent_work/predicate"
	"github.com/huoayi/business-center-ent-private/pkg/ent_work/product"
	"github.com/huoayi/business-center-ent-private/pkg/ent_work/user"
	"github.com/huoayi/business-center-ent-private/pkg/enum"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetCreatedBy sets the "created_by" field.
func (ou *OrderUpdate) SetCreatedBy(i int64) *OrderUpdate {
	ou.mutation.ResetCreatedBy()
	ou.mutation.SetCreatedBy(i)
	return ou
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableCreatedBy(i *int64) *OrderUpdate {
	if i != nil {
		ou.SetCreatedBy(*i)
	}
	return ou
}

// AddCreatedBy adds i to the "created_by" field.
func (ou *OrderUpdate) AddCreatedBy(i int64) *OrderUpdate {
	ou.mutation.AddCreatedBy(i)
	return ou
}

// SetUpdatedBy sets the "updated_by" field.
func (ou *OrderUpdate) SetUpdatedBy(i int64) *OrderUpdate {
	ou.mutation.ResetUpdatedBy()
	ou.mutation.SetUpdatedBy(i)
	return ou
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableUpdatedBy(i *int64) *OrderUpdate {
	if i != nil {
		ou.SetUpdatedBy(*i)
	}
	return ou
}

// AddUpdatedBy adds i to the "updated_by" field.
func (ou *OrderUpdate) AddUpdatedBy(i int64) *OrderUpdate {
	ou.mutation.AddUpdatedBy(i)
	return ou
}

// SetUpdatedAt sets the "updated_at" field.
func (ou *OrderUpdate) SetUpdatedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetUpdatedAt(t)
	return ou
}

// SetDeletedAt sets the "deleted_at" field.
func (ou *OrderUpdate) SetDeletedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetDeletedAt(t)
	return ou
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableDeletedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetDeletedAt(*t)
	}
	return ou
}

// SetCount sets the "count" field.
func (ou *OrderUpdate) SetCount(i int64) *OrderUpdate {
	ou.mutation.ResetCount()
	ou.mutation.SetCount(i)
	return ou
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableCount(i *int64) *OrderUpdate {
	if i != nil {
		ou.SetCount(*i)
	}
	return ou
}

// AddCount adds i to the "count" field.
func (ou *OrderUpdate) AddCount(i int64) *OrderUpdate {
	ou.mutation.AddCount(i)
	return ou
}

// SetAmount sets the "amount" field.
func (ou *OrderUpdate) SetAmount(i int64) *OrderUpdate {
	ou.mutation.ResetAmount()
	ou.mutation.SetAmount(i)
	return ou
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableAmount(i *int64) *OrderUpdate {
	if i != nil {
		ou.SetAmount(*i)
	}
	return ou
}

// AddAmount adds i to the "amount" field.
func (ou *OrderUpdate) AddAmount(i int64) *OrderUpdate {
	ou.mutation.AddAmount(i)
	return ou
}

// SetAddress sets the "address" field.
func (ou *OrderUpdate) SetAddress(s string) *OrderUpdate {
	ou.mutation.SetAddress(s)
	return ou
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableAddress(s *string) *OrderUpdate {
	if s != nil {
		ou.SetAddress(*s)
	}
	return ou
}

// SetProductsID sets the "products_id" field.
func (ou *OrderUpdate) SetProductsID(i int64) *OrderUpdate {
	ou.mutation.SetProductsID(i)
	return ou
}

// SetNillableProductsID sets the "products_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableProductsID(i *int64) *OrderUpdate {
	if i != nil {
		ou.SetProductsID(*i)
	}
	return ou
}

// SetUserID sets the "user_id" field.
func (ou *OrderUpdate) SetUserID(i int64) *OrderUpdate {
	ou.mutation.SetUserID(i)
	return ou
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableUserID(i *int64) *OrderUpdate {
	if i != nil {
		ou.SetUserID(*i)
	}
	return ou
}

// SetStatus sets the "status" field.
func (ou *OrderUpdate) SetStatus(es enum.OrderStatus) *OrderUpdate {
	ou.mutation.SetStatus(es)
	return ou
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableStatus(es *enum.OrderStatus) *OrderUpdate {
	if es != nil {
		ou.SetStatus(*es)
	}
	return ou
}

// SetProducts sets the "products" edge to the Product entity.
func (ou *OrderUpdate) SetProducts(p *Product) *OrderUpdate {
	return ou.SetProductsID(p.ID)
}

// SetUser sets the "user" edge to the User entity.
func (ou *OrderUpdate) SetUser(u *User) *OrderUpdate {
	return ou.SetUserID(u.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// ClearProducts clears the "products" edge to the Product entity.
func (ou *OrderUpdate) ClearProducts() *OrderUpdate {
	ou.mutation.ClearProducts()
	return ou
}

// ClearUser clears the "user" edge to the User entity.
func (ou *OrderUpdate) ClearUser() *OrderUpdate {
	ou.mutation.ClearUser()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OrderUpdate) defaults() {
	if _, ok := ou.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		ou.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent_work: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := ou.mutation.ProductsID(); ou.mutation.ProductsCleared() && !ok {
		return errors.New(`ent_work: clearing a required unique edge "Order.products"`)
	}
	if _, ok := ou.mutation.UserID(); ou.mutation.UserCleared() && !ok {
		return errors.New(`ent_work: clearing a required unique edge "Order.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ou *OrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdate {
	ou.modifiers = append(ou.modifiers, modifiers...)
	return ou
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.CreatedBy(); ok {
		_spec.SetField(order.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.AddedCreatedBy(); ok {
		_spec.AddField(order.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.UpdatedBy(); ok {
		_spec.SetField(order.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(order.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ou.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if value, ok := ou.mutation.Count(); ok {
		_spec.SetField(order.FieldCount, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.AddedCount(); ok {
		_spec.AddField(order.FieldCount, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.Address(); ok {
		_spec.SetField(order.FieldAddress, field.TypeString, value)
	}
	if value, ok := ou.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if ou.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductsTable,
			Columns: []string{order.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductsTable,
			Columns: []string{order.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ou.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ou.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedBy sets the "created_by" field.
func (ouo *OrderUpdateOne) SetCreatedBy(i int64) *OrderUpdateOne {
	ouo.mutation.ResetCreatedBy()
	ouo.mutation.SetCreatedBy(i)
	return ouo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableCreatedBy(i *int64) *OrderUpdateOne {
	if i != nil {
		ouo.SetCreatedBy(*i)
	}
	return ouo
}

// AddCreatedBy adds i to the "created_by" field.
func (ouo *OrderUpdateOne) AddCreatedBy(i int64) *OrderUpdateOne {
	ouo.mutation.AddCreatedBy(i)
	return ouo
}

// SetUpdatedBy sets the "updated_by" field.
func (ouo *OrderUpdateOne) SetUpdatedBy(i int64) *OrderUpdateOne {
	ouo.mutation.ResetUpdatedBy()
	ouo.mutation.SetUpdatedBy(i)
	return ouo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableUpdatedBy(i *int64) *OrderUpdateOne {
	if i != nil {
		ouo.SetUpdatedBy(*i)
	}
	return ouo
}

// AddUpdatedBy adds i to the "updated_by" field.
func (ouo *OrderUpdateOne) AddUpdatedBy(i int64) *OrderUpdateOne {
	ouo.mutation.AddUpdatedBy(i)
	return ouo
}

// SetUpdatedAt sets the "updated_at" field.
func (ouo *OrderUpdateOne) SetUpdatedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetUpdatedAt(t)
	return ouo
}

// SetDeletedAt sets the "deleted_at" field.
func (ouo *OrderUpdateOne) SetDeletedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetDeletedAt(t)
	return ouo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableDeletedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetDeletedAt(*t)
	}
	return ouo
}

// SetCount sets the "count" field.
func (ouo *OrderUpdateOne) SetCount(i int64) *OrderUpdateOne {
	ouo.mutation.ResetCount()
	ouo.mutation.SetCount(i)
	return ouo
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableCount(i *int64) *OrderUpdateOne {
	if i != nil {
		ouo.SetCount(*i)
	}
	return ouo
}

// AddCount adds i to the "count" field.
func (ouo *OrderUpdateOne) AddCount(i int64) *OrderUpdateOne {
	ouo.mutation.AddCount(i)
	return ouo
}

// SetAmount sets the "amount" field.
func (ouo *OrderUpdateOne) SetAmount(i int64) *OrderUpdateOne {
	ouo.mutation.ResetAmount()
	ouo.mutation.SetAmount(i)
	return ouo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableAmount(i *int64) *OrderUpdateOne {
	if i != nil {
		ouo.SetAmount(*i)
	}
	return ouo
}

// AddAmount adds i to the "amount" field.
func (ouo *OrderUpdateOne) AddAmount(i int64) *OrderUpdateOne {
	ouo.mutation.AddAmount(i)
	return ouo
}

// SetAddress sets the "address" field.
func (ouo *OrderUpdateOne) SetAddress(s string) *OrderUpdateOne {
	ouo.mutation.SetAddress(s)
	return ouo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableAddress(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetAddress(*s)
	}
	return ouo
}

// SetProductsID sets the "products_id" field.
func (ouo *OrderUpdateOne) SetProductsID(i int64) *OrderUpdateOne {
	ouo.mutation.SetProductsID(i)
	return ouo
}

// SetNillableProductsID sets the "products_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableProductsID(i *int64) *OrderUpdateOne {
	if i != nil {
		ouo.SetProductsID(*i)
	}
	return ouo
}

// SetUserID sets the "user_id" field.
func (ouo *OrderUpdateOne) SetUserID(i int64) *OrderUpdateOne {
	ouo.mutation.SetUserID(i)
	return ouo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableUserID(i *int64) *OrderUpdateOne {
	if i != nil {
		ouo.SetUserID(*i)
	}
	return ouo
}

// SetStatus sets the "status" field.
func (ouo *OrderUpdateOne) SetStatus(es enum.OrderStatus) *OrderUpdateOne {
	ouo.mutation.SetStatus(es)
	return ouo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableStatus(es *enum.OrderStatus) *OrderUpdateOne {
	if es != nil {
		ouo.SetStatus(*es)
	}
	return ouo
}

// SetProducts sets the "products" edge to the Product entity.
func (ouo *OrderUpdateOne) SetProducts(p *Product) *OrderUpdateOne {
	return ouo.SetProductsID(p.ID)
}

// SetUser sets the "user" edge to the User entity.
func (ouo *OrderUpdateOne) SetUser(u *User) *OrderUpdateOne {
	return ouo.SetUserID(u.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// ClearProducts clears the "products" edge to the Product entity.
func (ouo *OrderUpdateOne) ClearProducts() *OrderUpdateOne {
	ouo.mutation.ClearProducts()
	return ouo
}

// ClearUser clears the "user" edge to the User entity.
func (ouo *OrderUpdateOne) ClearUser() *OrderUpdateOne {
	ouo.mutation.ClearUser()
	return ouo
}

// Where appends a list predicates to the OrderUpdate builder.
func (ouo *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	ouo.defaults()
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OrderUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		ouo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent_work: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := ouo.mutation.ProductsID(); ouo.mutation.ProductsCleared() && !ok {
		return errors.New(`ent_work: clearing a required unique edge "Order.products"`)
	}
	if _, ok := ouo.mutation.UserID(); ouo.mutation.UserCleared() && !ok {
		return errors.New(`ent_work: clearing a required unique edge "Order.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ouo *OrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdateOne {
	ouo.modifiers = append(ouo.modifiers, modifiers...)
	return ouo
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent_work: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent_work: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.CreatedBy(); ok {
		_spec.SetField(order.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.AddedCreatedBy(); ok {
		_spec.AddField(order.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.UpdatedBy(); ok {
		_spec.SetField(order.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(order.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.Count(); ok {
		_spec.SetField(order.FieldCount, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.AddedCount(); ok {
		_spec.AddField(order.FieldCount, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.Address(); ok {
		_spec.SetField(order.FieldAddress, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if ouo.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductsTable,
			Columns: []string{order.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductsTable,
			Columns: []string{order.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ouo.modifiers...)
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
