// Code generated by ent, DO NOT EDIT.

package ent_work

import (
	"time"

	"github.com/huoayi/business-center-ent-private/pkg/ent_work/schema"
	"github.com/huoayi/business-center-ent-private/pkg/ent_work/user"
	"github.com/huoayi/business-center-ent-private/pkg/ent_work/vxsocial"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedBy is the schema descriptor for created_by field.
	userDescCreatedBy := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedBy holds the default value on creation for the created_by field.
	user.DefaultCreatedBy = userDescCreatedBy.Default.(int64)
	// userDescUpdatedBy is the schema descriptor for updated_by field.
	userDescUpdatedBy := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	user.DefaultUpdatedBy = userDescUpdatedBy.Default.(int64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescDeletedAt is the schema descriptor for deleted_at field.
	userDescDeletedAt := userMixinFields0[5].Descriptor()
	// user.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	user.DefaultDeletedAt = userDescDeletedAt.Default.(time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescNickName is the schema descriptor for nick_name field.
	userDescNickName := userFields[1].Descriptor()
	// user.DefaultNickName holds the default value on creation for the nick_name field.
	user.DefaultNickName = userDescNickName.Default.(string)
	// userDescJpgURL is the schema descriptor for jpg_url field.
	userDescJpgURL := userFields[2].Descriptor()
	// user.DefaultJpgURL holds the default value on creation for the jpg_url field.
	user.DefaultJpgURL = userDescJpgURL.Default.(string)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[3].Descriptor()
	// user.DefaultPhone holds the default value on creation for the phone field.
	user.DefaultPhone = userDescPhone.Default.(string)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[4].Descriptor()
	// user.DefaultPassword holds the default value on creation for the password field.
	user.DefaultPassword = userDescPassword.Default.(string)
	// userDescIsFrozen is the schema descriptor for is_frozen field.
	userDescIsFrozen := userFields[5].Descriptor()
	// user.DefaultIsFrozen holds the default value on creation for the is_frozen field.
	user.DefaultIsFrozen = userDescIsFrozen.Default.(bool)
	// userDescIsRecharge is the schema descriptor for is_recharge field.
	userDescIsRecharge := userFields[6].Descriptor()
	// user.DefaultIsRecharge holds the default value on creation for the is_recharge field.
	user.DefaultIsRecharge = userDescIsRecharge.Default.(bool)
	// userDescPopVersion is the schema descriptor for pop_version field.
	userDescPopVersion := userFields[8].Descriptor()
	// user.DefaultPopVersion holds the default value on creation for the pop_version field.
	user.DefaultPopVersion = userDescPopVersion.Default.(string)
	// userDescAreaCode is the schema descriptor for area_code field.
	userDescAreaCode := userFields[9].Descriptor()
	// user.DefaultAreaCode holds the default value on creation for the area_code field.
	user.DefaultAreaCode = userDescAreaCode.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[10].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescCloudSpace is the schema descriptor for cloud_space field.
	userDescCloudSpace := userFields[11].Descriptor()
	// user.DefaultCloudSpace holds the default value on creation for the cloud_space field.
	user.DefaultCloudSpace = userDescCloudSpace.Default.(int64)
	// userDescParentID is the schema descriptor for parent_id field.
	userDescParentID := userFields[12].Descriptor()
	// user.DefaultParentID holds the default value on creation for the parent_id field.
	user.DefaultParentID = userDescParentID.Default.(int64)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() int64)
	vxsocialMixin := schema.VXSocial{}.Mixin()
	vxsocialMixinFields0 := vxsocialMixin[0].Fields()
	_ = vxsocialMixinFields0
	vxsocialFields := schema.VXSocial{}.Fields()
	_ = vxsocialFields
	// vxsocialDescCreatedBy is the schema descriptor for created_by field.
	vxsocialDescCreatedBy := vxsocialMixinFields0[1].Descriptor()
	// vxsocial.DefaultCreatedBy holds the default value on creation for the created_by field.
	vxsocial.DefaultCreatedBy = vxsocialDescCreatedBy.Default.(int64)
	// vxsocialDescUpdatedBy is the schema descriptor for updated_by field.
	vxsocialDescUpdatedBy := vxsocialMixinFields0[2].Descriptor()
	// vxsocial.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	vxsocial.DefaultUpdatedBy = vxsocialDescUpdatedBy.Default.(int64)
	// vxsocialDescCreatedAt is the schema descriptor for created_at field.
	vxsocialDescCreatedAt := vxsocialMixinFields0[3].Descriptor()
	// vxsocial.DefaultCreatedAt holds the default value on creation for the created_at field.
	vxsocial.DefaultCreatedAt = vxsocialDescCreatedAt.Default.(func() time.Time)
	// vxsocialDescUpdatedAt is the schema descriptor for updated_at field.
	vxsocialDescUpdatedAt := vxsocialMixinFields0[4].Descriptor()
	// vxsocial.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vxsocial.DefaultUpdatedAt = vxsocialDescUpdatedAt.Default.(func() time.Time)
	// vxsocial.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vxsocial.UpdateDefaultUpdatedAt = vxsocialDescUpdatedAt.UpdateDefault.(func() time.Time)
	// vxsocialDescDeletedAt is the schema descriptor for deleted_at field.
	vxsocialDescDeletedAt := vxsocialMixinFields0[5].Descriptor()
	// vxsocial.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	vxsocial.DefaultDeletedAt = vxsocialDescDeletedAt.Default.(time.Time)
	// vxsocialDescAppID is the schema descriptor for app_id field.
	vxsocialDescAppID := vxsocialFields[0].Descriptor()
	// vxsocial.DefaultAppID holds the default value on creation for the app_id field.
	vxsocial.DefaultAppID = vxsocialDescAppID.Default.(string)
	// vxsocialDescOpenID is the schema descriptor for open_id field.
	vxsocialDescOpenID := vxsocialFields[1].Descriptor()
	// vxsocial.DefaultOpenID holds the default value on creation for the open_id field.
	vxsocial.DefaultOpenID = vxsocialDescOpenID.Default.(string)
	// vxsocialDescUnionID is the schema descriptor for union_id field.
	vxsocialDescUnionID := vxsocialFields[2].Descriptor()
	// vxsocial.DefaultUnionID holds the default value on creation for the union_id field.
	vxsocial.DefaultUnionID = vxsocialDescUnionID.Default.(string)
	// vxsocialDescSessionKey is the schema descriptor for session_key field.
	vxsocialDescSessionKey := vxsocialFields[4].Descriptor()
	// vxsocial.DefaultSessionKey holds the default value on creation for the session_key field.
	vxsocial.DefaultSessionKey = vxsocialDescSessionKey.Default.(string)
	// vxsocialDescAccessToken is the schema descriptor for access_token field.
	vxsocialDescAccessToken := vxsocialFields[5].Descriptor()
	// vxsocial.DefaultAccessToken holds the default value on creation for the access_token field.
	vxsocial.DefaultAccessToken = vxsocialDescAccessToken.Default.(string)
	// vxsocialDescRefreshToken is the schema descriptor for refresh_token field.
	vxsocialDescRefreshToken := vxsocialFields[6].Descriptor()
	// vxsocial.DefaultRefreshToken holds the default value on creation for the refresh_token field.
	vxsocial.DefaultRefreshToken = vxsocialDescRefreshToken.Default.(string)
	// vxsocialDescUserID is the schema descriptor for user_id field.
	vxsocialDescUserID := vxsocialFields[7].Descriptor()
	// vxsocial.DefaultUserID holds the default value on creation for the user_id field.
	vxsocial.DefaultUserID = vxsocialDescUserID.Default.(int64)
	// vxsocialDescID is the schema descriptor for id field.
	vxsocialDescID := vxsocialMixinFields0[0].Descriptor()
	// vxsocial.DefaultID holds the default value on creation for the id field.
	vxsocial.DefaultID = vxsocialDescID.Default.(func() int64)
}
